development:
  adapter: postgresql
  database: templates_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: templates_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: templates_production
  pool: 5
  timeout: 5000